<?php

declare(strict_types=1);

require __DIR__ . '/../src/App/App.php';

if (isset($_GET['logout'])) {
    new \App\Controller\User\Logout();
    header("Location: /");
}
?>

<?php require_once __DIR__ . '/partials/head.phtml'; ?>

<body>
    <div>
        <?php require_once __DIR__ . '/partials/nav.phtml'; ?>
    </div>

    <h1>Perfil</h1>

    <div>
        <?php require_once __DIR__ . '/partials/footer.phtml'; ?>
    </div>
</body>

</html>